uploads = []
generated = []

[[outputs]]
id = "oPiNfUdJ1XH_nVCl3Qcom"
uri = "file://VetSystem_Инвестиционное_описание.md"
type = "text"
title = "VetSystem — Инвестиционное описание"

[[outputs]]
id = "jgR4kpQNBUSaLQ__EBl3T"
uri = "file://docs/user-manual.md"
type = "text"
title = "Инструкция пользователя VetSystemAI"

[[outputs]]
id = "Ew4-3UB6AXb6u5xJRKo4n"
uri = "file://docs/VetSystemAI_User_Manual.docx"
type = "word_document"
title = "VetSystemAI — Руководство пользователя (.docx)"
