uploads = []
generated = []

[[outputs]]
id = "oPiNfUdJ1XH_nVCl3Qcom"
uri = "file://VetSystem_Инвестиционное_описание.md"
type = "text"
title = "VetSystem — Инвестиционное описание"

[[outputs]]
id = "jgR4kpQNBUSaLQ__EBl3T"
uri = "file://docs/user-manual.md"
type = "text"
title = "Инструкция пользователя VetSystemAI"

[[outputs]]
id = "Ew4-3UB6AXb6u5xJRKo4n"
uri = "file://docs/VetSystemAI_User_Manual.docx"
type = "word_document"
title = "VetSystemAI — Руководство пользователя (.docx)"

[[outputs]]
id = "Cyists6K3hboVxAiEBzpI"
uri = "file://docs/VetSystemAI_Technologies.docx"
type = "word_document"
title = "VetSystemAI — Описание технологического стека"

[[outputs]]
id = "eWkk_B9T5jD71ZUBl4M9z"
uri = "file://docs/VetSystemAI_Website_Specification.docx"
type = "word_document"
title = "VetSystemAI — Спецификация веб-приложения"
